/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotfoundImport } from './routes/notfound'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminChristianityCategoriesIndexImport } from './routes/admin/christianity/categories/index'
import { Route as AdminChristianityArticlesIndexImport } from './routes/admin/christianity/articles/index'
import { Route as AdminChristianityArticlesNewArticleImport } from './routes/admin/christianity/articles/new-article'
import { Route as AdminChristianityArticlesSlugIndexImport } from './routes/admin/christianity/articles/$slug/index'
import { Route as AdminChristianityArticlesSlugNewTranslationIndexImport } from './routes/admin/christianity/articles/$slug/new-translation/index'
import { Route as AdminChristianityArticlesSlugLangIndexImport } from './routes/admin/christianity/articles/$slug/$lang/index'

// Create/Update Routes

const NotfoundRoute = NotfoundImport.update({
  id: '/notfound',
  path: '/notfound',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminChristianityCategoriesIndexRoute =
  AdminChristianityCategoriesIndexImport.update({
    id: '/christianity/categories/',
    path: '/christianity/categories/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

const AdminChristianityArticlesIndexRoute =
  AdminChristianityArticlesIndexImport.update({
    id: '/christianity/articles/',
    path: '/christianity/articles/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

const AdminChristianityArticlesNewArticleRoute =
  AdminChristianityArticlesNewArticleImport.update({
    id: '/christianity/articles/new-article',
    path: '/christianity/articles/new-article',
    getParentRoute: () => AdminRouteRoute,
  } as any)

const AdminChristianityArticlesSlugIndexRoute =
  AdminChristianityArticlesSlugIndexImport.update({
    id: '/christianity/articles/$slug/',
    path: '/christianity/articles/$slug/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

const AdminChristianityArticlesSlugNewTranslationIndexRoute =
  AdminChristianityArticlesSlugNewTranslationIndexImport.update({
    id: '/christianity/articles/$slug/new-translation/',
    path: '/christianity/articles/$slug/new-translation/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

const AdminChristianityArticlesSlugLangIndexRoute =
  AdminChristianityArticlesSlugLangIndexImport.update({
    id: '/christianity/articles/$slug/$lang/',
    path: '/christianity/articles/$slug/$lang/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/notfound': {
      id: '/notfound'
      path: '/notfound'
      fullPath: '/notfound'
      preLoaderRoute: typeof NotfoundImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/christianity/articles/new-article': {
      id: '/admin/christianity/articles/new-article'
      path: '/christianity/articles/new-article'
      fullPath: '/admin/christianity/articles/new-article'
      preLoaderRoute: typeof AdminChristianityArticlesNewArticleImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/christianity/articles/': {
      id: '/admin/christianity/articles/'
      path: '/christianity/articles'
      fullPath: '/admin/christianity/articles'
      preLoaderRoute: typeof AdminChristianityArticlesIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/christianity/categories/': {
      id: '/admin/christianity/categories/'
      path: '/christianity/categories'
      fullPath: '/admin/christianity/categories'
      preLoaderRoute: typeof AdminChristianityCategoriesIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/christianity/articles/$slug/': {
      id: '/admin/christianity/articles/$slug/'
      path: '/christianity/articles/$slug'
      fullPath: '/admin/christianity/articles/$slug'
      preLoaderRoute: typeof AdminChristianityArticlesSlugIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/christianity/articles/$slug/$lang/': {
      id: '/admin/christianity/articles/$slug/$lang/'
      path: '/christianity/articles/$slug/$lang'
      fullPath: '/admin/christianity/articles/$slug/$lang'
      preLoaderRoute: typeof AdminChristianityArticlesSlugLangIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/christianity/articles/$slug/new-translation/': {
      id: '/admin/christianity/articles/$slug/new-translation/'
      path: '/christianity/articles/$slug/new-translation'
      fullPath: '/admin/christianity/articles/$slug/new-translation'
      preLoaderRoute: typeof AdminChristianityArticlesSlugNewTranslationIndexImport
      parentRoute: typeof AdminRouteImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChristianityArticlesNewArticleRoute: typeof AdminChristianityArticlesNewArticleRoute
  AdminChristianityArticlesIndexRoute: typeof AdminChristianityArticlesIndexRoute
  AdminChristianityCategoriesIndexRoute: typeof AdminChristianityCategoriesIndexRoute
  AdminChristianityArticlesSlugIndexRoute: typeof AdminChristianityArticlesSlugIndexRoute
  AdminChristianityArticlesSlugLangIndexRoute: typeof AdminChristianityArticlesSlugLangIndexRoute
  AdminChristianityArticlesSlugNewTranslationIndexRoute: typeof AdminChristianityArticlesSlugNewTranslationIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminChristianityArticlesNewArticleRoute:
    AdminChristianityArticlesNewArticleRoute,
  AdminChristianityArticlesIndexRoute: AdminChristianityArticlesIndexRoute,
  AdminChristianityCategoriesIndexRoute: AdminChristianityCategoriesIndexRoute,
  AdminChristianityArticlesSlugIndexRoute:
    AdminChristianityArticlesSlugIndexRoute,
  AdminChristianityArticlesSlugLangIndexRoute:
    AdminChristianityArticlesSlugLangIndexRoute,
  AdminChristianityArticlesSlugNewTranslationIndexRoute:
    AdminChristianityArticlesSlugNewTranslationIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/notfound': typeof NotfoundRoute
  '/admin/': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin/christianity/articles/new-article': typeof AdminChristianityArticlesNewArticleRoute
  '/admin/christianity/articles': typeof AdminChristianityArticlesIndexRoute
  '/admin/christianity/categories': typeof AdminChristianityCategoriesIndexRoute
  '/admin/christianity/articles/$slug': typeof AdminChristianityArticlesSlugIndexRoute
  '/admin/christianity/articles/$slug/$lang': typeof AdminChristianityArticlesSlugLangIndexRoute
  '/admin/christianity/articles/$slug/new-translation': typeof AdminChristianityArticlesSlugNewTranslationIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notfound': typeof NotfoundRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin/christianity/articles/new-article': typeof AdminChristianityArticlesNewArticleRoute
  '/admin/christianity/articles': typeof AdminChristianityArticlesIndexRoute
  '/admin/christianity/categories': typeof AdminChristianityCategoriesIndexRoute
  '/admin/christianity/articles/$slug': typeof AdminChristianityArticlesSlugIndexRoute
  '/admin/christianity/articles/$slug/$lang': typeof AdminChristianityArticlesSlugLangIndexRoute
  '/admin/christianity/articles/$slug/new-translation': typeof AdminChristianityArticlesSlugNewTranslationIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/notfound': typeof NotfoundRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/christianity/articles/new-article': typeof AdminChristianityArticlesNewArticleRoute
  '/admin/christianity/articles/': typeof AdminChristianityArticlesIndexRoute
  '/admin/christianity/categories/': typeof AdminChristianityCategoriesIndexRoute
  '/admin/christianity/articles/$slug/': typeof AdminChristianityArticlesSlugIndexRoute
  '/admin/christianity/articles/$slug/$lang/': typeof AdminChristianityArticlesSlugLangIndexRoute
  '/admin/christianity/articles/$slug/new-translation/': typeof AdminChristianityArticlesSlugNewTranslationIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/notfound'
    | '/admin/'
    | '/login'
    | '/admin/christianity/articles/new-article'
    | '/admin/christianity/articles'
    | '/admin/christianity/categories'
    | '/admin/christianity/articles/$slug'
    | '/admin/christianity/articles/$slug/$lang'
    | '/admin/christianity/articles/$slug/new-translation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notfound'
    | '/admin'
    | '/login'
    | '/admin/christianity/articles/new-article'
    | '/admin/christianity/articles'
    | '/admin/christianity/categories'
    | '/admin/christianity/articles/$slug'
    | '/admin/christianity/articles/$slug/$lang'
    | '/admin/christianity/articles/$slug/new-translation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/notfound'
    | '/admin/'
    | '/login/'
    | '/admin/christianity/articles/new-article'
    | '/admin/christianity/articles/'
    | '/admin/christianity/categories/'
    | '/admin/christianity/articles/$slug/'
    | '/admin/christianity/articles/$slug/$lang/'
    | '/admin/christianity/articles/$slug/new-translation/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  NotfoundRoute: typeof NotfoundRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  NotfoundRoute: NotfoundRoute,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/notfound",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/",
        "/admin/christianity/articles/new-article",
        "/admin/christianity/articles/",
        "/admin/christianity/categories/",
        "/admin/christianity/articles/$slug/",
        "/admin/christianity/articles/$slug/$lang/",
        "/admin/christianity/articles/$slug/new-translation/"
      ]
    },
    "/notfound": {
      "filePath": "notfound.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/admin/christianity/articles/new-article": {
      "filePath": "admin/christianity/articles/new-article.tsx",
      "parent": "/admin"
    },
    "/admin/christianity/articles/": {
      "filePath": "admin/christianity/articles/index.tsx",
      "parent": "/admin"
    },
    "/admin/christianity/categories/": {
      "filePath": "admin/christianity/categories/index.tsx",
      "parent": "/admin"
    },
    "/admin/christianity/articles/$slug/": {
      "filePath": "admin/christianity/articles/$slug/index.tsx",
      "parent": "/admin"
    },
    "/admin/christianity/articles/$slug/$lang/": {
      "filePath": "admin/christianity/articles/$slug/$lang/index.tsx",
      "parent": "/admin"
    },
    "/admin/christianity/articles/$slug/new-translation/": {
      "filePath": "admin/christianity/articles/$slug/new-translation/index.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
